[build]
  publish = "dist/portfolio/browser"
  command = "npm run build"

[[redirects]]
  from = "/og/*"
  to = "/og/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200